"""add audio processing fields

Revision ID: b169ef294c5f
Revises: 6185c244957e
Create Date: 2026-10-01 16:29:32.721147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b169ef294c5f'
down_revision: Union[str, Sequence[str], None] = '6185c244957e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_notes', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.add_column('audio_notes', sa.Column('gnani_job_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_notes', 'gnani_job_id')
    op.drop_column('audio_notes', 'duration_seconds')
    # ### end Alembic commands ###
